name: 'Open weekly issue'
description: 'Create new release issue when the last one was closed'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  template-path:
    description: 'Relative path to the weekly template'
    required: true
    default: '.github/ISSUE_TEMPLATE/WEEKLY_NOTE.md'
runs:
  using: 'node16'
  main: 'index.js'