name: 'Setup'
description: 'Performs CI setup for bpmn.io projects'
runs:
  using: "composite"
  steps:
    - name: Setup chromium sandbox
      if: runner.os == 'Linux'
      shell: bash
      run: |
        SANDBOX_LOCATION=/opt/google/chrome/chrome-sandbox

        sudo chown root $SANDBOX_LOCATION
        sudo chmod 4755 $SANDBOX_LOCATION

        echo "CHROME_DEVEL_SANDBOX=$SANDBOX_LOCATION" >> "$GITHUB_ENV"
