name: Update latest branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-latest:
    runs-on: ubuntu-latest
    name: Fast-forward latest to main
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update latest
        run: git push origin HEAD:latest --force
